---
title: "Visualizations Assignment"
author: "Chase LaDue"
date: "4/3/2018"
output: html_document
---

First, I'll start with the code that was given in `working_example.Rmd`.

```{r package-data}

library(tidyverse) # loading package

sjer_veg <- read_csv("data/D17_2013_SJER_vegStr.csv") # loading data

```

Now, let's plot the graph that we'll be starting with.

```{r base-graph}

g <- sjer_veg %>% 
  select(maxcanopydiam, stemheight, livingcanopy) %>% 
  ggplot(aes(x = stemheight, y = maxcanopydiam)) + 
    geom_point(aes(color = livingcanopy)) +
    scale_color_gradient(low = "red", high = "green")

g # view graph

```

Let's start off by providing appropriate labels for the title, axes, and legend.

```{r labels}

# data description is available in file "veg_metadata_desc_DataInstitute2016.csv"

g.1 <- g +
  scale_color_gradient(low = "red", high = "green", name = "% of canopy alive") + # legend label
  xlab("Distance from ground to highest stem (m)") + # added x-axis label
  ylab("Maximum canopy diameter (m)") + # added y-axis label
  ggtitle("Relationship between\nCanopy Diameter and Distance to Highest Stem") # graph title

g.1 # view updated graph
```

